dicars_logistica_registrar_ingreso_producto:
    pattern:  /registrar_ingreso_producto
    defaults: { _controller: DicarsLogisticaBundle:AdministrarIngresoProd:RegistrarIngresoProd }
    requirements:
          _method: POST
dicars_logistica_editar_ingreso_producto:
    pattern:  /registrar_editar_producto
    defaults: { _controller: DicarsLogisticaBundle:AdministrarIngresoProd:EditarIngresoProd }
    requirements:
          _method: POST 