dicars_logistica_registrar_proveedor:
    pattern:  /registrar_proveedor
    defaults: { _controller: DicarsLogisticaBundle:AdministrarProveedor:RegistrarProveedor }
    requirements:
          _method: POST