dicars_logistica_registrar_producto:
    pattern:  /registrar_producto
    defaults: { _controller: DicarsLogisticaBundle:AdministrarProducto:RegistrarProducto }
    requirements:
          _method: POST
          
dicars_logistica_editar_producto:
    pattern:  /editar_producto
    defaults: { _controller: DicarsLogisticaBundle:AdministrarProducto:EditarProducto }
    requirements:
          _method: POST