dicars_logistica_registrar_ordcompra:
    pattern:  /registrar_ordcompra
    defaults: { _controller: DicarsLogisticaBundle:AdministrarOrdCompra:RegistrarOrdCompra }
    requirements:
          _method: POST