dicars_logistica_homepage:
    pattern:  /index
    defaults: { _controller: DicarsLogisticaBundle:Default:index }
dicars_logistica_productos:
    pattern:  /productos
    defaults: { _controller: DicarsLogisticaBundle:Default:productos }