logistica_servicio_routing:
    resource: "@DicarsLogisticaBundle/Resources/config/servicios_routing.yml"
    
logistica_administrar_proveedor_routing:
    resource: "@DicarsLogisticaBundle/Resources/config/administrar_proveedor_routing.yml"

logistica_administrar_producto_routing:
    resource: "@DicarsLogisticaBundle/Resources/config/administrar_producto_routing.yml"
    
logistica_administrar_local_routing:
    resource: "@DicarsLogisticaBundle/Resources/config/administrar_local_routing.yml"
    
logistica_administrar_pedido_routing:
    resource: "@DicarsLogisticaBundle/Resources/config/administrar_pedido_routing.yml"

dicars_logistica_homepage:
    pattern:  /index
    defaults: { _controller: DicarsLogisticaBundle:Default:index }
dicars_logistica_productos:
    pattern:  /productos
    defaults: { _controller: DicarsLogisticaBundle:Default:productos }
dicars_logistica_proveedores:
    pattern:  /proveedores
    defaults: { _controller: DicarsLogisticaBundle:Default:proveedores }
dicars_logistica_locales:
    pattern:  /locales
    defaults: { _controller: DicarsLogisticaBundle:Default:locales }
dicars_logistica_cons_salidaproductos:
    pattern:  /cons_salidaproductos
    defaults: { _controller: DicarsLogisticaBundle:Default:cons_salidaproductos }
dicars_logistica_reg_salidaproductos:
    pattern:  /reg_salidaproductos
    defaults: { _controller: DicarsLogisticaBundle:Default:reg_salidaproductos }
dicars_logistica_cons_ingresoproductos:
    pattern:  /cons_ingresoproductos
    defaults: { _controller: DicarsLogisticaBundle:Default:cons_ingresoproductos }  
dicars_logistica_reg_ingresoproductos:
    pattern:  /reg_ingresoproductos
    defaults: { _controller: DicarsLogisticaBundle:Default:reg_ingresoproductos }  
dicars_logistica_registrar_producto:
    pattern:  /registrar_producto
    defaults: { _controller: DicarsLogisticaBundle:AdministrarProducto:RegistrarProducto }
dicars_logistica_pedidos:
    pattern:  /pedidos
    defaults: { _controller: DicarsLogisticaBundle:Default:pedidos }
dicars_logistica_pedidos_registrar:
    pattern:  /pedidos_registrar
    defaults: { _controller: DicarsLogisticaBundle:Default:pedidos_registrar }
