parameters:
#    dicars_logistica.example.class: Dicars\LogisticaBundle\Example

services:
#    dicars_logistica.example:
#        class: %dicars_logistica.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
