dicars_logistica_servicio_gettablaproductos:
    pattern:  /servicio_gettablaproductos
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaProductos }
    
dicars_logistica_servicio_getproductobyid:
    pattern:  /servicio_getproductobyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getProductoById }
    
dicars_logistica_servicio_gettablaproveedores:
    pattern:  /servicio_gettablaproveedores
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaProveedores }
    
dicars_logistica_servicio_getproveedorbyid:
    pattern:  /servicio_getproveedorbyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getProveedorById }
    
dicars_logistica_servicio_gettablalocales:
    pattern:  /servicio_gettablalocales
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaLocales }
    
dicars_logistica_servicio_getlocalbyid:
    pattern:  /servicio_getlocalbyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getLocalById }
    
dicars_logistica_servicio_gettablaingresoproducto:
    pattern:  /servicio_gettablaingresoproducto/{fecmin}/{fecmax}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaIngresoProducto }

dicars_logistica_servicio_gettablasalprods:
    pattern:  /servicio_gettablasalprods/{fecmin}/{fecmax}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaSalProd }

dicars_logistica_servicio_gettabladetsalprod:
    pattern:  /servicio_gettabladetsalprod/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaDetSalProd }

dicars_logistica_servicio_gettablaordpeds:
    pattern:  /servicio_gettablaordpeds
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaPedidos }
    
dicars_logistica_servicio_gettabladetordped:
    pattern:  /servicio_gettabladetordped/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaDetOrdPed }

dicars_logistica_servicio_gettabladetingprod:
    pattern:  /servicio_gettabladetingprod/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaDetIngProd }    

dicars_logistica_servicio_getoptionlocal:
    pattern:  /servicio_getoptionlocal
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getOptionLocales }  
    
dicars_logistica_servicio_gettablaordcom:
    pattern:  /servicio_gettablaordcom/{fecmin}/{fecmax}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaOrdCom }
    
dicars_logistica_servicio_gettabladetordcom:
    pattern:  /servicio_gettabladetordcom/{idordcom}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaDetOrdCom }
    
dicars_logistica_servicio_gettabladetpedidocompra:
    pattern:  /servicio_gettabladetpedidocompra
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaDetPedidoCompra }
    
dicars_logistica_servicio_getgenerarcodigoprducto:
    pattern:  /servicio_getgenerarcodigoprducto
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getGenerarCodigoProducto }
    
dicars_logistica_servicio_getgenerarcodigopedido:
    pattern:  /servicio_getgenerarcodigopedido
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getGenerarCodigoPedido }
    
dicars_logistica_servicio_getgenerarcodigosalprod:
    pattern:  /servicio_getgenerarcodigosalprod
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getGenerarCodigoSalProd }
    
dicars_logistica_servicio_getgenerarcodigoingprod:
    pattern:  /servicio_getgenerarcodigoingprod
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getGenerarCodigoIngProd }