dicars_logistica_servicio_gettablaproductos:
    pattern:  /servicio_gettablaproductos
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaProductos }
    
dicars_logistica_servicio_getproductobyid:
    pattern:  /servicio_getproductobyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getProductoById }
    
dicars_logistica_servicio_gettablaproveedores:
    pattern:  /servicio_gettablaproveedores
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaProveedores }
    
dicars_logistica_servicio_getproveedorbyid:
    pattern:  /servicio_getproveedorbyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getProveedorById }
    
dicars_logistica_servicio_gettablalocales:
    pattern:  /servicio_gettablalocales
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaLocales }
    
dicars_logistica_servicio_getlocalbyid:
    pattern:  /servicio_getlocalbyid/{id}
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getLocalById }
    
dicars_logistica_servicio_gettablaingresoproducto:
    pattern:  /servicio_gettablaingresoproducto
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaIngresoProducto }

dicars_logistica_servicio_gettablasalprods:
    pattern:  /servicio_gettablasalprods
    defaults: { _controller: DicarsLogisticaBundle:LogisticaServicios:getTablaSalProd }