dicars_admin_registrar_constante:
    pattern:  /registrar_constante    
    defaults: { _controller: DicarsAdminBundle:AdministrarConstantes:RegistrarConstante }
    requirements:
          _method: POST
dicars_admin_editar_constante:
    pattern:  /editar_constante    
    defaults: { _controller: DicarsAdminBundle:AdministrarConstantes:EditarConstante }
    requirements:
          _method: POST