dicars_admin_registrar_categoria:
    pattern:  /registrar_categoria
    defaults: { _controller: DicarsAdminBundle:AdministrarCategorias:RegistrarCategoria }
    requirements:
          _method: POST
dicars_admin_editar_categoria:
    pattern:  /editar_categoria
    defaults: { _controller: DicarsAdminBundle:AdministrarCategorias:EditarCategoria }
    requirements:
          _method: POST