dicars_admin_registrar_usuario:
    pattern:  /registrar_usuario    
    defaults: { _controller: DicarsAdminBundle:AdministrarUsuario:RegistrarUsuario }
    requirements:
          _method: POST
          
dicars_admin_editar_usuario:
    pattern:  /editar_usuario
    defaults: { _controller: DicarsAdminBundle:AdministrarUsuario:EditarUsuario }
    requirements:
          _method: POST
          
dicars_admin_usuarios:
    pattern: /usuarios
    defaults: { _controller: DicarsAdminBundle:Default:usuario }   
    
dicars_admin_roles:
    pattern: /admin_roles
    defaults: {_controller: DicarsAdminBundle:AdministrarUsuario:AdminRoles}
    requirements:
          _method: POST