dicars_admin_registrar_tipoigv:
    pattern:  /registrar_tipoigv    
    defaults: { _controller: DicarsAdminBundle:AdministrarTipoIGV:RegistrarTipoIGV }
    requirements:
          _method: POST
dicars_admin_editar_tipoigv:
    pattern:  /editar_tipoigv    
    defaults: { _controller: DicarsAdminBundle:AdministrarTipoIGV:EditarTipoIGV }
    requirements:
          _method: POST