dicars_admin_registrar_zona:
    pattern:  /registrar_zona
    defaults: { _controller: DicarsAdminBundle:AdministrarZona:RegistrarZona }
    requirements:
          _method: POST
dicars_admin_editar_zona:
    pattern:  /editar_zona
    defaults: { _controller: DicarsAdminBundle:AdministrarZona:EditarZona }
    requirements:
          _method: POST