dicars_admin_registrar_cargo:
    pattern:  /registrar_cargo
    defaults: { _controller: DicarsAdminBundle:AdministrarCargo:RegistrarCargo }
    requirements:
          _method: POST
dicars_admin_editar_cargo:
    pattern:  /editar_cargo
    defaults: { _controller: DicarsAdminBundle:AdministrarCargo:EditarCargo }
    requirements:
          _method: POST