admin_administrar_cargo_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_cargo_routing.yml"
admin_administrar_categoria_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_categoria_routing.yml"
admin_administrar_marca_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_marca_routing.yml"
admin_administrar_zona_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_zona_routing.yml"
admin_administrar_servicios_routing:
    resource: "@DicarsAdminBundle/Resources/config/servicios_routing.yml"
admin_administrar_constante_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_constante_routing.yml"

admin_administrar_tipomoneda_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_tipomoneda_routing.yml"
    
ventas_administrar_usuario_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_usuario_routing.yml"
    
admin_administrar_tipoigv_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_tipoigv_routing.yml"    
    
admin_administrar_zonapersonal:
    resource: "@DicarsAdminBundle/Resources/config/administrar_zonapersonal.yml"  
admin_administrar_movimiento_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_mov_routing.yml"  

dicars_admin_homepage:
    pattern:  /index
    defaults: { _controller: DicarsAdminBundle:Default:index }
dicars_reportes_homepage:
    pattern:  /reportes
    defaults: { _controller: DicarsAdminBundle:Default:reportesindex }
dicars_admin_constantes:
    pattern:  /constantes
    defaults: { _controller: DicarsAdminBundle:Default:constantes }
dicars_admin_cargos:
    pattern:  /cargos
    defaults: { _controller: DicarsAdminBundle:Default:cargos }
dicars_admin_usuarios:
    pattern:  /usuarios
    defaults: { _controller: DicarsAdminBundle:Default:usuarios }
dicars_admin_categorias:
    pattern:  /categorias
    defaults: { _controller: DicarsAdminBundle:Default:categorias }
dicars_admin_marcas:
    pattern:  /marcas
    defaults: { _controller: DicarsAdminBundle:Default:marcas }
dicars_admin_zonas:
    pattern:  /zonas
    defaults: { _controller: DicarsAdminBundle:Default:zonas }
dicars_admin_tipomoneda:
    pattern:  /tipomoneda
    defaults: { _controller: DicarsAdminBundle:Default:tipomoneda }
dicars_admin_tipoigv:
    pattern:  /tipoigv
    defaults: { _controller: DicarsAdminBundle:Default:tipoigv }
    
dicars_admin_zonapersonal:
    pattern:  /zonapersonal
    defaults: { _controller: DicarsAdminBundle:Default:ZonaPersonal }
    
dicars_admin_editar_zonapersonal_view:
    pattern:  /editar_zonapersonal_view/{idzonapersonal}
    defaults: { _controller: DicarsAdminBundle:Default:EditarZonaPersonal }
    
dicars_admin_movimientos:
    pattern:  /movimientos
    defaults: { _controller: DicarsAdminBundle:Default:movimientos }