admin_administrar_cargo_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_cargo_routing.yml"
admin_administrar_categoria_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_categoria_routing.yml"
admin_administrar_marca_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_marca_routing.yml"
admin_administrar_zona_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_zona_routing.yml"
admin_administrar_servicios_routing:
    resource: "@DicarsAdminBundle/Resources/config/servicios_routing.yml"
admin_administrar_constante_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_constante_routing.yml"
    
ventas_administrar_usuario_routing:
    resource: "@DicarsAdminBundle/Resources/config/administrar_usuario_routing.yml"
    
dicars_admin_homepage:
    pattern:  /index
    defaults: { _controller: DicarsAdminBundle:Default:index }
dicars_admin_constantes:
    pattern:  /constantes
    defaults: { _controller: DicarsAdminBundle:Default:constantes }
dicars_admin_cargos:
    pattern:  /cargos
    defaults: { _controller: DicarsAdminBundle:Default:cargos }
dicars_admin_usuarios:
    pattern:  /usuarios
    defaults: { _controller: DicarsAdminBundle:Default:usuarios }
dicars_admin_categorias:
    pattern:  /categorias
    defaults: { _controller: DicarsAdminBundle:Default:categorias }
dicars_admin_marcas:
    pattern:  /marcas
    defaults: { _controller: DicarsAdminBundle:Default:marcas }
dicars_admin_zonas:
    pattern:  /zonas
    defaults: { _controller: DicarsAdminBundle:Default:zonas }
