dicars_admin_servicio_gettablacargos:
    pattern:  /servicio_gettablacargos
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaCargos }
dicars_admin_servicio_getcargobyid:
    pattern:  /servicio_getcargobyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getCargoById }

dicars_admin_servicio_gettablacategorias:
    pattern:  /servicio_gettablacategorias
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaCategorias }
dicars_admin_servicio_getcategoriabyid:
    pattern:  /servicio_getcategoriabyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getCategoriaById }
dicars_admin_servicio_gettablamarcas:
    pattern:  /servicio_gettablamarcas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaMarcas }
dicars_admin_servicio_getmarcabyid:
    pattern:  /servicio_getmarcabyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getMarcaById }
dicars_admin_servicio_gettablausuario:
    pattern:  /servicio_gettablausuario
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaUsuario }
dicars_admin_servicio_getusuariobyid:
    pattern:  /servicio_getusuariobyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getUsuarioById }    
dicars_admin_servicio_getoptionmarcas:
    pattern:  /servicio_getoptionmarcas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionMarcas }
dicars_admin_servicio_getoptioncategorias:
    pattern:  /servicio_getoptioncategorias
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionCategorias } 
dicars_admin_servicio_gettablaconstantes:
    pattern:  /servicio_gettablaconstantes
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaConstantes }
dicars_admin_servicio_gettablazonas:
    pattern:  /servicio_gettablazonas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaZonas }
dicars_admin_servicio_gettablatipomoneda:
    pattern:  /servicio_gettipomoneda
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaTipoMoneda }
dicars_admin_servicio_getconstantebyid:
    pattern:  /servicio_getconstantebyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getConstanteById }
    
dicars_admin_servicio_getoptiontipobyclase:
    pattern:  /servicio_getoptiontipobyclase/{Clase}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionTipoByClase }  
    
dicars_admin_servicio_getoptiontiprubs:
    pattern:  /servicio_getoptiontiprubs
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionTipoRubro }

dicars_admin_servicio_getoptionubigeo:
    pattern:  /servicio_getoptionubigeo
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionUbigeo }
    
dicars_admin_servicio_getoptionconstantes:
    pattern:  /servicio_getoptionconstantes/{idclase}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionConstantes }

dicars_admin_servicio_getoptionzonas:
    pattern:  /servicio_getoptionzonas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionZonas }

dicars_admin_servicio_getoptioncargos:
    pattern:  /servicio_getoptioncargos
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionCargos }
    
dicars_admin_servicio_getoptiontiposigv:
    pattern:  /servicio_getoptiontiposigv
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionTiposIGV }