dicars_admin_servicio_gettablacargos:
    pattern:  /servicio_gettablacargos
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaCargos }
dicars_admin_servicio_getcargobyid:
    pattern:  /servicio_getcargobyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getCargoById }

dicars_admin_servicio_gettablacategorias:
    pattern:  /servicio_gettablacategorias
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaCategorias }
dicars_admin_servicio_getcategoriabyid:
    pattern:  /servicio_getcategoriabyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getCategoriaById }
dicars_admin_servicio_gettablamarcas:
    pattern:  /servicio_gettablamarcas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaMarcas }
dicars_admin_servicio_getmarcabyid:
    pattern:  /servicio_getmarcabyid/{id}
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getMarcaById }
dicars_admin_servicio_gettablausuario:
    pattern:  /servicio_gettablausuario
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getTablaUsuario }
dicars_admin_servicio_getoptionmarcas:
    pattern:  /servicio_getoptionmarcas
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionMarcas }
dicars_admin_servicio_getoptioncategorias:
    pattern:  /servicio_getoptioncategorias
    defaults: { _controller: DicarsAdminBundle:AdministrarServicios:getOptionCategorias } 