dicars_ventas_registrar_cliente:
    pattern:  /registrar_cliente
    defaults: { _controller: DicarsVentasBundle:AdministrarClientes:RegistrarCliente }
    requirements:
          _method: POST
          
dicars_logistica_editar_cliente:
    pattern:  /editar_cliente
    defaults: { _controller: DicarsLogisticaBundle:AdministrarClientes:EditarCliente }
    requirements:
          _method: POST          