dicars_ventas_homepage:
    pattern:  /index
    defaults: { _controller: DicarsVentasBundle:Default:index }
dicars_ventas_clientes:
    pattern: /clientes
    defaults: { _controller: DicarsVentasBundle:Default:cliente }