dicars_ventas_homepage:
    pattern:  /index
    defaults: { _controller: DicarsVentasBundle:Default:index }
dicars_ventas_clientes:
    pattern: /clientes
    defaults: { _controller: DicarsVentasBundle:Default:clientes }
dicars_ventas_clientes_dm:
    pattern: /clientes_dm
    defaults: { _controller: DicarsVentasBundle:Default:clientes_dm }
dicars_ventas_trabajadores:
    pattern: /trabajadores
    defaults: { _controller: DicarsVentasBundle:Default:trabajadores }
dicars_ventas_separar_productos:
    pattern: /separar_productos
    defaults: { _controller: DicarsVentasBundle:Default:separar_productos }
dicars_ventas_regimp_tarjetacredito:
    pattern: /regimp_tarjetacredito
    defaults: { _controller: DicarsVentasBundle:Default:regimp_tarjetacredito }