ventas_servicio_routing:
    resource: "@DicarsVentasBundle/Resources/config/servicios_routing.yml"

ventas_administrar_cliente_routing:
    resource: "@DicarsVentasBundle/Resources/config/administrar_cliente_routing.yml"
    
ventas_administrar_trabajador_routing:
    resource: "@DicarsVentasBundle/Resources/config/administrar_trabajador_routing.yml"
    
ventas_administrar_oferta_routing:
    resource: "@DicarsVentasBundle/Resources/config/administrar_oferta_routing.yml"   

ventas_administrar_venta_routing:
    resource: "@DicarsVentasBundle/Resources/config/administrar_venta_routing.yml"   

ventas_administrar_cronograma_routing:
    resource: "@DicarsVentasBundle/Resources/config/administrar_cronograma_routing.yml"   

dicars_ventas_homepage:
    pattern:  /index
    defaults: { _controller: DicarsVentasBundle:Default:index }
dicars_ventas_clientes:
    pattern: /clientes
    defaults: { _controller: DicarsVentasBundle:Default:clientes }
dicars_ventas_clientes_dm:
    pattern: /clientes_dm
    defaults: { _controller: DicarsVentasBundle:Default:clientes_dm }
dicars_ventas_trabajadores:
    pattern: /trabajadores
    defaults: { _controller: DicarsVentasBundle:Default:trabajadores }
dicars_ventas_separar_productos:
    pattern: /separar_productos
    defaults: { _controller: DicarsVentasBundle:Default:separar_productos }
dicars_ventas_regimp_tarjetacredito:
    pattern: /regimp_tarjetacredito
    defaults: { _controller: DicarsVentasBundle:Default:regimp_tarjetacredito }
dicars_ventas_cronograma:
    pattern: /cronograma
    defaults: { _controller: DicarsVentasBundle:Default:cronograma }
dicars_ventas_cronograma_creditos:
    pattern: /cronograma_creditos/{idcliente}
    defaults: { _controller: DicarsVentasBundle:Default:cronograma_creditos }
dicars_ventas_ingregr_dia:
    pattern: /ingregr_dia
    defaults: { _controller: DicarsVentasBundle:Default:ingregr_dia }
dicars_ventas_reporte_zonas:
    pattern: /reporte_zonas
    defaults: { _controller: DicarsVentasBundle:Default:reporte_zonas }
dicars_ventas_control_salidas_zonas:
    pattern: /control_salidas_zonas
    defaults: { _controller: DicarsVentasBundle:Default:control_salidasZonas }
dicars_ventas_venta_productos:
    pattern: /venta_productos
    defaults: { _controller: DicarsVentasBundle:Default:venta_productos }
dicars_ventas_resumen_venta:
    pattern: /resumen_venta
    defaults: { _controller: DicarsVentasBundle:Default:resumen_venta }
dicars_ventas_view_editar_oferta:
    pattern: /view_editar_oferta/{idoferta}
    defaults: { _controller: DicarsVentasBundle:Default:editar_oferta }  
dicars_ventas_ofertas:
    pattern: /ofertas
    defaults: { _controller: DicarsVentasBundle:Default:ofertas }
dicars_ventas_consultar:
    pattern: /venta_consultar
    defaults: { _controller: DicarsVentasBundle:Default:venta_consultar }
dicars_ventas_ver:
    pattern: /venta_ver/{idventa}
    defaults: { _controller: DicarsVentasBundle:Default:venta_ver }
    
dicars_ventas_editar:
    pattern: /venta_editar/{idventa}
    defaults: { _controller: DicarsVentasBundle:Default:venta_editar }
    
dicars_ventas_reporte:
    pattern: /venta_reporte
    defaults: { _controller: DicarsVentasBundle:Default:ventas_reporte }