dicars_ventas_servicio_gettablaclientes:
    pattern:  /servicio_gettablaclientes
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaClientes }
    
dicars_ventas_servicio_gettablaempleados:
    pattern:  /servicio_gettablaempleados
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaEmpleados }    
    
dicars_ventas_servicio_getclientebyid:
    pattern:  /servicio_getclientebyid/{id}
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getClienteById }
    
dicars_ventas_servicio_gettrabajadorbyid:
    pattern:  /servicio_gettrabajadorbyid/{id}
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTrabajadorById } 