dicars_ventas_servicio_gettablaclientes:
    pattern:  /servicio_gettablaclientes
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaClientes }
    
dicars_ventas_servicio_gettablaempleados:
    pattern:  /servicio_gettablaempleados
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaEmpleados }    
    
dicars_ventas_servicio_getclientebyid:
    pattern:  /servicio_getclientebyid/{id}
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getClienteById }
    
dicars_ventas_servicio_gettrabajadorbyid:
    pattern:  /servicio_gettrabajadorbyid/{id}
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTrabajadorById }
    
dicars_ventas_servicio_getventaproductosoferta:
    pattern:  /servicio_getventaproductosoferta
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaVentaProductoOferta } 

dicars_ventas_servicio_gettablaofertas:
    pattern:  /servicio_gettablaofertas
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaOfertas }
    
dicars_ventas_servicio_getventaproductossinoferta:
    pattern:  /servicio_getventaproductossinoferta
    defaults: { _controller: DicarsVentasBundle:VentaServicios:getTablaVentaProductoSinOferta } 