dicars_movil:
    resource: "@DicarsMovilBundle/Resources/config/routing.yml"
    prefix:   /api/

_user_bundle:
  resource: "@UserBundle/Resources/config/routing.yml"
  prefix: /

dicars_admin:
    resource: "@DicarsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

dicars_login:
    resource: "@DicarsLoginBundle/Resources/config/routing.yml"
    prefix:   /

dicars_contabilidad:
    resource: "@DicarsContabilidadBundle/Resources/config/routing.yml"
    prefix:   /contabilidad/

dicars_logistica:
    resource: "@DicarsLogisticaBundle/Resources/config/routing.yml"
    prefix:   /logistica/

dicars_ventas:
    resource: "@DicarsVentasBundle/Resources/config/routing.yml"
    prefix:   /ventas/

dicars_data:
    resource: "@DicarsDataBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
