jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Dicards\DataBundle\Entity\Usuario: 
          algorithm: sha512
          encode-as-base64: true
          iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       user_db:
         entity: {class: Dicars\DataBundle\Entity\Usuario, property: cusuarioid}
         
    

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          pattern: /.*
          form_login:
            login_path: /ingreso
            check_path: /ingreso_check
            remember_me: true
            default_target_path: /main
          logout:
            path: /salir
            target: /ingreso

          remember_me:
            key: MiPassphrase
            lifetime: 1800
            path: /.*
            domain: ~
          security: true
          anonymous: true
                
         
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/ingreso, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/sobre, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/contacto, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/contacto_up, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
       # - {path: /user, roles: ROLE_USER }
#        - {path: /admin, roles: ROLE_ADMIN}
 #       - {path: /.*, roles: ROLE_USER ,requires_channel: https }
