jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_JVENTA, ROLE_JLOG, ROLE_JSOP]
        ROLE_JVENTA: [ROLE_VENDEDOR, ROLE_COBRANZA]
        ROLE_JLOG: [ROLE_ASIST_ALM, ROLE_ASIST_KARD]
        ROLE_JSOP: [ROLE_SUPORT_VENTA, ROLE_SUPORT_RH]
        ROLE_VENDEDOR: [ROLE_USER]
        ROLE_COBRANZA: [ROLE_USER]
        ROLE_ASIST_ALM: [ROLE_USER]
        ROLE_ASIST_KARD: [ROLE_USER]
        ROLE_SUPORT_VENTA: [ROLE_USER]
        ROLE_SUPORT_RH: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       fos_userbundle:
            id: fos_user.user_provider.username    
      

    firewalls:
    
        api:
          pattern: ^/api/.*
          stateless: true
          security: true
          http_basic:
            realm: "API"
          
        main:
          pattern: /.*
          form_login:
            check_path: /login_check
            login_path: /login
            default_target_path: /home
            provider: fos_userbundle
          logout:
            path: /logout
            target: /
          anonymous: ~

          remember_me:
            key: MiPassphrase
            lifetime: 1800
            path: /.*
            domain: ~
          security: true
          anonymous: true
                
         
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/sobre, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/contacto, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/contacto_up, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: /api/, role: ROLE_USER }
       # - {path: /user, roles: ROLE_USER }
#        - {path: /admin, roles: ROLE_ADMIN}
        - {path: /home, roles: ROLE_USER ,requires_channel: https }
