parameters:
#    dicars_contabilidad.example.class: Dicars\ContabilidadBundle\Example

services:
#    dicars_contabilidad.example:
#        class: %dicars_contabilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
