parameters:
#    dicars_data.example.class: Dicars\DataBundle\Example

services:
#    dicars_data.example:
#        class: %dicars_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
